project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "STAT 250 Lab Primers"
  description: "Practice for your STAT 250 Labs"
  site-url: "https://csumb-stat-ds.github.io/stat-250-lab-primers"
  repo-url: https://github.com/csumb-stat-ds/stat-250-lab-primers
  repo-actions: [issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Judith Canner"
    background: "#D9E3E4"

  sidebar:
#    background: "#5D737E"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/csumb-stat-ds/stat-250-lab-primers
        text: "GitHub organization"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
    - href: index.qmd
      text: "Home"
    - section: "General Lab Instructions"
      contents:
      - href: instructions/importing-exporting.qmd
        text: "Lab Workflow"      
      - href: 
        text: "R Code Style Guide"
      - href: 
        text: "Common Errors"
    - section: "Getting Started with R"
      contents:
      - href: prep-materials/rstudio-orientation.qmd
        text: "RStudio Orientation"    
      - href: prep-materials/intro-to-quarto.qmd
        text: "Introduction to Quarto"
      - href: prep-materials/install-r.qmd
        text: "Optional: Install R and RStudio"        
    - section: "Lab Primers"  
      contents: 
      - href: lab-1-primer/lab-1-intro-r-primer.qmd
        text: "Lab 1 Primer"
      - href: lab-2-primer/lab-2-eda-primer.qmd
        text: "Lab 2 Primer"
      - href: lab-3-primer/lab-3-intro-inference-primer.qmd
        text: "Lab 3 Primer"
      - href: lab-4-primer/lab-4-confidence-primer.qmd
        text: "Lab 4 Primer"
      # - href: 
      #   text: "Lab 5 Primer"
      # - href: 
      #   text: "Lab 6 Primer"      
      # - href: 
      #   text: "Lab 7 Primer"        
      # - href: 
      #   text: "Lab 8 Primer"        
      # - href: 
      #   text: "Lab 9 Primer"        
      # - href: 
      #   text: "Lab 10 Primer"        
      # - href: 
      #   text: "Lab 11 Primer"
      # - href: 
      #   text: "Lab 12 Primer"
       
format:
  html:
    theme: "minty"
    mainfont: "sans-serif"
    code-copy: true
    code-overflow: wrap
    toc: true
    css: styles.css  
#    linkcolor: "#5D737E"
#    highlight-style: a11y-dark

editor: source

