project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "STAT 250 Lab Primers"
  description: "A Guide to Introductory Statistics Tools in R"
  site-url: "https://jcanner.github.io/how-to-do-it-in-R"
  repo-url: https://github.com/jcanner/how-to-do-it-in-R
  repo-actions: [issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Judith Canner"
    background: "#D9E3E4"

  sidebar:
#    background: "#5D737E"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/jcanner/how-to-do-it-in-R
        text: "GitHub organization"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
    - href: index.qmd
      text: "Home"
    - section: "General Lab Instructions"
      contents:
      - href: overview/code-style-guide.qmd
        text: "R Code Style Guide"
    - section: "Lab Primers"  
      contents: 
      - href: data-visualization/visualization-overview.qmd
        text: "Lab 1 Primer"
      - href: data-visualization/histograms.qmd
        text: "Lab 2 Primer"
      - href: data-visualization/boxplots.qmd
        text: "Boxplots"
      - href: data-visualization/scatterplots.qmd
        text: "Scatterplots"
      - href: data-visualization/barplots.qmd
        text: "Bar Plots"

    - section: "Summary Statistics with `mosaic`"  
      contents: 
      - href: summary-statistics/summary-stats-overview.qmd
        text: "Overview of `mosaic`"
      - href: summary-statistics/measures-of-center.qmd
        text: "Measures of Center"
      - href: summary-statistics/measures-of-spread.qmd
        text: "Measures of Spread"
      - href: summary-statistics/measures-of-relationship.qmd
        text: "Measures of Relationship"
      - href: summary-statistics/measures-of-frequency.qmd
        text: "Measures of Frequency"
      - href: summary-statistics/generating-multiple-stats.qmd
        text: "Generating Multiple Statistics (`df_stats`)"

    - section: "Inference and Conditions"  
      contents: 
      - href: inference/inference-overview.qmd
        text: "Overview of `mosaic`"
      - href: inference/one-mean.qmd
        text: "Confidence Interval - One Mean"
      - href: inference/two-means.qmd
        text: "Independent Two Sample Inference"
      - href: inference/paired-mean.qmd
        text: "Matched Pairs Inference"
      - href: inference/multiple-means.qmd
        text: "Analysis of Variance"
      - href: inference/slope.qmd
        text: "Simple Linear Regression"
      - href: inference/multiple-proportions.qmd
        text: "Chi-Square Goodness of Fit"
      
format:
  html:
    theme: "minty"
    mainfont: "sans-serif"
    code-copy: true
    code-overflow: wrap
    toc: true
    css: styles.css  
#    linkcolor: "#5D737E"
#    highlight-style: a11y-dark

editor: source

